name: "Terraform CI/CD DESTROY Infra"

on: workflow_dispatch

jobs:
    terraform:
      name: 'Terraform'
      runs-on: ubuntu-latest
      env:
        working-directory: eks 
      defaults:
        run:
          shell: bash
          working-directory: ${{ env.working-directory }}

      steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Install Terraform latest
          uses: hashicorp/setup-terraform@v2

        - name: Terraform Init
          run: terraform init

        - name: Terraform Format
          run: terraform fmt -check
          continue-on-error: true

        - name: Terraform validate
          run: terraform validate

        - name: Terraform Plan
          run: terraform plan -input=false

        - name: Terraform Destroy
          run: terraform destroy -auto-approve -input=false